2019/04/12 16:37:55 [emerg] 14385#14385: directive "init_by_lua_file" is not terminated by ";" in /root/work/conf/nginx.conf:11
2019/04/12 16:38:23 [error] 14427#14427: init_by_lua_file error: /root/work/lua/init.lua:4: expecting 3, 4 or 5 arguments, but only seen 2
stack traceback:
	[C]: in function 'set'
	/root/work/lua/init.lua:4: in main chunk
2019/04/12 16:40:52 [error] 14658#14658: init_by_lua_file error: /root/work/lua/init.lua:6: expecting 3, 4 or 5 arguments, but only seen 2
stack traceback:
	[C]: in function 'set'
	/root/work/lua/init.lua:6: in main chunk
2019/04/12 16:52:08 [error] 15886#15886: *1 "/root/work/html/index.html" is forbidden (13: Permission denied), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:52:12 [error] 15886#15886: *2 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:52:27 [error] 15886#15886: *3 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:52:55 [error] 15886#15886: *4 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:53:41 [error] 15886#15886: *5 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:53:55 [alert] 15885#15885: worker process 15886 exited on signal 9
2019/04/12 16:54:27 [error] 16088#16088: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:28 [error] 16088#16088: *2 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:29 [error] 16088#16088: *3 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:30 [error] 16088#16088: *4 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:31 [error] 16088#16088: *5 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:32 [error] 16088#16088: *6 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:54:33 [error] 16088#16088: *7 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:00 [error] 16226#16226: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:01 [error] 16226#16226: *2 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:03 [error] 16226#16226: *3 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua/ HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:05 [error] 16226#16226: *4 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:06 [error] 16226#16226: *5 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:07 [error] 16226#16226: *6 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:08 [error] 16226#16226: *7 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:09 [error] 16226#16226: *8 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:10 [error] 16226#16226: *9 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:30 [error] 16226#16226: *10 "/root/work/html/index.html" is forbidden (13: Permission denied), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:30 [error] 16226#16226: *10 open() "/root/work/html/favicon.ico" failed (13: Permission denied), client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:56:34 [error] 16226#16226: *10 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 16:57:08 [error] 16226#16226: *10 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:18 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:19 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:20 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:20 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:21 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:21 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:21 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:21 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:22 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:22 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:22 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:22 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:23 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:23 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:23 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:01:32 [error] 16657#16657: *1 failed to load external Lua file "/root/work/lua/test.lua": cannot open /root/work/lua/test.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 17:04:59 [error] 16985#16985: init_by_lua_file error: /opt/lua/init.lua:6: expecting 3, 4 or 5 arguments, but only seen 2
stack traceback:
	[C]: in function 'set'
	/opt/lua/init.lua:6: in main chunk
2019/04/12 17:12:50 [emerg] 17532#17532: unexpected ";" in /root/work/conf/nginx.conf:15
2019/04/12 17:13:10 [error] 17552#17552: init_by_lua error: init_by_lua:7: expecting 3, 4 or 5 arguments, but only seen 2
stack traceback:
	[C]: in function 'set'
	init_by_lua:7: in main chunk
2019/04/12 17:15:21 [emerg] 17718#17718: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 17:15:21 [emerg] 17718#17718: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 17:15:21 [emerg] 17718#17718: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 17:15:21 [emerg] 17718#17718: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 17:15:21 [emerg] 17718#17718: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 17:15:21 [emerg] 17718#17718: still could not bind()
2019/04/12 21:30:34 [error] 39115#39115: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 21:30:34 [error] 39115#39115: *1 attempt to send data on a closed socket: u:0000000041ACA160, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 21:30:34 [error] 39115#39115: *1 attempt to send data on a closed socket: u:0000000041ACA160, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: , request: "GET /lua HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 21:30:35 [error] 39115#39115: *1 open() "/root/work/html/favicon.ico" failed (13: Permission denied), client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8080"
2019/04/12 21:35:49 [emerg] 39936#39936: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 21:35:49 [emerg] 39936#39936: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 21:35:49 [emerg] 39936#39936: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 21:35:49 [emerg] 39936#39936: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 21:35:49 [emerg] 39936#39936: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:11:11 [notice] 42447#42447: signal process started
2019/04/12 22:11:28 [notice] 42464#42464: signal process started
2019/04/12 22:13:53 [emerg] 42659#42659: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:13:53 [emerg] 42659#42659: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:13:53 [emerg] 42659#42659: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:13:53 [emerg] 42659#42659: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:13:53 [emerg] 42659#42659: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2019/04/12 22:13:53 [emerg] 42659#42659: still could not bind()
2019/04/12 22:13:59 [notice] 42667#42667: signal process started
2019/04/12 22:16:04 [notice] 42801#42801: signal process started
2019/04/12 22:23:50 [notice] 43352#43352: signal process started
2019/04/12 22:25:00 [notice] 43432#43432: signal process started
2019/04/12 22:25:48 [notice] 43488#43488: signal process started
2019/04/12 22:27:16 [notice] 43583#43583: signal process started
2019/04/12 22:44:55 [notice] 44849#44849: signal process started
2019/04/13 17:44:49 [notice] 59922#59922: signal process started
